### ISSUE TITLE
Cluster ECH1, UQCRFS1, SARS2: exploration for MorphMap paper (ORF+CRISPR)

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/jump_hub#16]
This cluster was found in #7 as strong (+/-) correlation in both ORF and CRISPR but not (completely) strongly connected in the KG. 

Looking across ORF and CRISPR plots there, there are a few other adjacent genes we should consider adding to this and then figure out a story for them (if needed, contacting a biologist who studies some subset of these genes).

![image](https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/assets/144879479/5a5c82bf-7ca2-4d21-a3af-4ebc5f8946d8)

For CRISPR, UQCRFS1  is p-value replicable. Otherwise, all genes are q-value replicable (for ORF & CRISPR). 

**Edited by Tomasz Jetka: updated title and image according to update in https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/7#issuecomment-1901252123 **

**Comment by AnneCarpenter** [comment]
Alan has gathered some info about the genes here: 
https://docs.google.com/document/d/1zKkDpBWbb3NnQhlX34LEWuuZxy5Rotre5uuuBMTxvxY/edit#heading=h.92upd2fec7b1

The 3 core genes mentioned in the issue title are tightly linked in ORF and CRISPR; the other genes shown for ORf and CRISPR are non-overlapping so we will probably drop them. 

The 3 core genes are relatively known to be involved with each other (KG scores .446, .638) except  ECH1 and SARS2 less so with KG .343 so that would be the one potential 'discovery' here. 

This site shows the two genes are the top nearest neighbours of each other based on cell line RNA expression:
https://www.proteinatlas.org/ENSG00000104823-ECH1/cell+line

It's possible some quick searches might reveal other links from other data sources.

The 3 genes are mitochondrial-related so this relationship seems supported by extra info and could be presented as a brief story, just needs synthesis/writing up.

**Comment by niranjchandrasekaran** [comment]
We will discuss the exploration of the story in [this doc](https://docs.google.com/document/d/1zKkDpBWbb3NnQhlX34LEWuuZxy5Rotre5uuuBMTxvxY/edit?usp=sharing) (private link)

**Comment by jgaetz-plex** [comment]
https://plexsearch.com/search#tab=pathway&ids=entrezgene%3A102436&ids=entrezgene%3A10247&ids=entrezgene%3A10295&ids=entrezgene%3A106557&ids=entrezgene%3A110115&ids=entrezgene%3A11370&ids=entrezgene%3A117145&ids=entrezgene%3A118451&ids=entrezgene%3A12036&ids=entrezgene%3A12040&ids=entrezgene%3A12041&ids=entrezgene%3A12352&ids=entrezgene%3A124454&ids=entrezgene%3A129868&ids=entrezgene%3A13081&ids=entrezgene%3A15473&ids=entrezgene%3A1584&ids=entrezgene%3A1591&ids=entrezgene%3A160760&ids=entrezgene%3A1716&ids=entrezgene%3A18604&ids=entrezgene%3A18673&ids=entrezgene%3A1891&ids=entrezgene%3A219927&ids=entrezgene%3A22228&ids=entrezgene%3A223722&ids=entrezgene%3A223726&ids=entrezgene%3A223915&ids=entrezgene%3A225791&ids=entrezgene%3A227682&ids=entrezgene%3A229211&ids=entrezgene%3A233870&ids=entrezgene%3A23395&ids=entrezgene%3A23409&ids=entrezgene%3A25279&ids=entrezgene%3A25344&ids=entrezgene%3A25363&ids=entrezgene%3A26024&ids=entrezgene%3A2628&ids=entrezgene%3A2639&ids=entrezgene%3A26995&ids=entrezgene%3A270076&ids=entrezgene%3A27069&ids=entrezgene%3A272428&ids=entrezgene%3A27349&ids=entrezgene%3A27369&ids=entrezgene%3A284273&ids=entrezgene%3A286923&ids=entrezgene%3A28976&ids=entrezgene%3A290596&ids=entrezgene%3A291103&ids=entrezgene%3A291403&ids=entrezgene%3A293481&ids=entrezgene%3A294972&ids=entrezgene%3A294973&ids=entrezgene%3A29603&ids=entrezgene%3A29711&ids=entrezgene%3A297389&ids=entrezgene%3A298426&ids=entrezgene%3A298596&ids=entrezgene%3A300248&ids=entrezgene%3A300884&ids=entrezgene%3A300989&ids=entrezgene%3A304488&ids=entrezgene%3A304539&ids=entrezgene%3A304542&ids=entrezgene%3A305845&ids=entrezgene%3A309140&ids=entrezgene%3A309227&ids=entrezgene%3A309381&ids=entrezgene%3A315173&ids=entrezgene%3A319101&ids=entrezgene%3A320717&ids=entrezgene%3A353242&ids=entrezgene%3A360569&ids=entrezgene%3A360887&ids=entrezgene%3A361637&ids=entrezgene%3A361641&ids=entrezgene%3A361755&ids=entrezgene%3A361992&ids=entrezgene%3A362094&ids=entrezgene%3A362971&ids=entrezgene%3A364975&ids=entrezgene%3A366012&ids=entrezgene%3A369018&ids=entrezgene%3A37&ids=entrezgene%3A387338&ids=entrezgene%3A4285&ids=entrezgene%3A500892&ids=entrezgene%3A51116&ids=entrezgene%3A51409&ids=entrezgene%3A5164&ids=entrezgene%3A51798&ids=entrezgene%3A52064&ids=entrezgene%3A5245&ids=entrezgene%3A52535&ids=entrezgene%3A54233&ids=entrezgene%3A54315&ids=entrezgene%3A54938&ids=entrezgene%3A54988&ids=entrezgene%3A55178&ids=entrezgene%3A56454&ids=entrezgene%3A56922&ids=entrezgene%3A56997&ids=entrezgene%3A5832&ids=entrezgene%3A587&ids=entrezgene%3A594&ids=entrezgene%3A6390&ids=entrezgene%3A64203&ids=entrezgene%3A64526&ids=entrezgene%3A64745&ids=entrezgene%3A65111&ids=entrezgene%3A65151&ids=entrezgene%3A66092&ids=entrezgene%3A66400&ids=entrezgene%3A666731&ids=entrezgene%3A66694&ids=entrezgene%3A67092&ids=entrezgene%3A67390&ids=entrezgene%3A67417&ids=entrezgene%3A67426&ids=entrezgene%3A67680&ids=entrezgene%3A67856&ids=entrezgene%3A679944&ids=entrezgene%3A684538&ids=entrezgene%3A69536&ids=entrezgene%3A70478&ids=entrezgene%3A71799&ids=entrezgene%3A71984&ids=entrezgene%3A72039&ids=entrezgene%3A72181&ids=entrezgene%3A7284&ids=entrezgene%3A7351&ids=entrezgene%3A7386&ids=entrezgene%3A74580&ids=entrezgene%3A75387&ids=entrezgene%3A75778&ids=entrezgene%3A758&ids=entrezgene%3A763&ids=entrezgene%3A7818&ids=entrezgene%3A79746&ids=entrezgene%3A80142&ids=entrezgene%3A81530&ids=entrezgene%3A81660&ids=entrezgene%3A81684&ids=entrezgene%3A84266&ids=entrezgene%3A84274&ids=entrezgene%3A84795&ids=entrezgene%3A92292&ids=entrezgene%3A92483&ids=entrezgene%3A96979

**Comment by jgaetz-plex** [comment]
Of the 52 genes most similar to this cluster in our ORF dataset, the majority are mitochondria-associated ([GOCC_Mitochondrion](https://www.gsea-msigdb.org/gsea/msigdb/geneset_page.jsp?geneSetName=GOCC_MITOCHONDRION)), including 16 mitochondrial disease-associated genes ([Ochoa et al. 2023](https://pubmed.ncbi.nlm.nih.gov/36399499/)). Knockdown or overexpression of LINC00473, a regulator of lipolysis and mitochondrial respiration, was shown to downregulate 15 of these genes ([Tran et al. 2020](https://pubmed.ncbi.nlm.nih.gov/32440655/)), and knockdown of the mitochondrial chaperone PHB2 resulted in down-regulation of 14 of this 52 gene cluster.

**Comment by AnneCarpenter** [comment]
Great, here is the draft text put into the main paper accordingly. @niranjchandrasekaran ready for you to finalize figures, etc.

ECH1, UQCRFS1, SARS2 cluster and are implicated in mitochondrial function and cancer
We found that the three enzymes strongly correlated in both the ORF and CRISPR profiles: ECH1 (enoyl-CoA hydratase 1), UQCRFS1 (ubiquinol-cytochrome c reductase, Rieske iron-sulfur polypeptide 1), and SARS2 (seryl-tRNA synthetase 2, mitochondrial) (Fig Xx). The connections among them are not well-known; UQCRFS1 and SARS2 are connected in the knowledge graph via databases, not by literature reports, and the remaining connections show weak or low knowledge graph scores (Fig Xx). Some existing data supports these new connections: SARS2 is the most highly correlated gene with ECH1 in terms of cell line RNA expression; SARS2 and ECH1 are the 5th and 10th top matches respectively for UQCRFS1 (https://www.proteinatlas.org/ENSG00000104823-ECH1/cell+line). Analyzing the top 52 genes most similar to this cluster in the ORF dataset using the Plex web application, the majority are mitochondria-associated ([GOCC_Mitochondrion](https://www.gsea-msigdb.org/gsea/msigdb/geneset_page.jsp?geneSetName=GOCC_MITOCHONDRION)), including 16 mitochondrial disease-associated genes ([Ochoa et al. 2023](https://pubmed.ncbi.nlm.nih.gov/36399499/)). Knockdown or overexpression of LINC00473, a regulator of lipolysis and mitochondrial respiration, downregulates 15 of these genes ([Tran et al. 2020](https://pubmed.ncbi.nlm.nih.gov/32440655/)), and knockdown of the mitochondrial chaperone PHB2 downregulates 14 genes in the cluster ([Liu et al 2017](https://pubmed.ncbi.nlm.nih.gov/28504707/)). Additionally, in proteomic profiling data from cells treated with a library of 875 compounds, 5 of the 10 profiles with the greatest overlap with this 52 gene cluster were from inhibitors of the PI3K/MTOR pathway ([Mitchell et al. 2023](https://pubmed.ncbi.nlm.nih.gov/36593396/)), which regulates both mitochondrial function and biogenesis ([Morita et al. 2017](https://pubmed.ncbi.nlm.nih.gov/28918902/)). Given recent interest in UQCRFS1 as a mitochondrial-related oncology biomarker and drug target [(Sun et al. 2023)](https://paperpile.com/c/JBXnUK/BiHO), SARS2 and ECH1 merit attention as well.

**Comment by niranjchandrasekaran** [comment]
This story was included in the Morphmap paper.
