### ISSUE TITLE
Data sources link broken

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/jump_hub#61]
![Screenshot 2024-12-13 at 5 31 13 PM](https://github.com/user-attachments/assets/f2f2fd7d-de44-4b14-a3c0-355a8d5c24a6)

![Screenshot 2024-12-13 at 5 32 26 PM](https://github.com/user-attachments/assets/f2ac7657-a6a3-4da8-81b8-775f75c4ee26)

**Comment by afermg** [comment]
Fixed the metadata on the monorepo [commit](https://github.com/broadinstitute/monorepo/commit/992bb2ad6df06f208cda201ae0b178ca71f53f79). This arose when Shantanu and I moved the manifest csv one folder down.
